# Generated by Django 5.2.4 on 2025-07-12 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('workout_type', models.CharField(max_length=255)),
                ('total_duration', models.CharField(max_length=255)),
                ('warm_up', models.CharField(max_length=255)),
                ('cool_down', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydration_tips', models.CharField(max_length=255)),
                ('special_notes', models.CharField(max_length=255)),
                ('supplement_suggestions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.PositiveIntegerField(help_text='Height in centimeters')),
                ('current_weight', models.PositiveIntegerField(help_text='Current weight in kg')),
                ('target_weight', models.PositiveIntegerField(help_text='Target weight in kg')),
                ('fitness_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('nutrition_preference', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Ketogenic', 'Ketogenic'), ('Paleo', 'Paleo'), ('Balanced', 'Balanced'), ('No Preference', 'No Preference')], max_length=20)),
                ('primary_goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Weight Maintenance', 'Weight Maintenance'), ('Improve Endurance', 'Improve Endurance'), ('Build Strength', 'Build Strength')], max_length=20)),
                ('workout_days_per_week', models.PositiveIntegerField(help_text='Number of workout days per week (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('time_per_session', models.PositiveIntegerField(help_text='Time per session in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('daily_calories', models.CharField(blank=True, max_length=255, null=True)),
                ('daily_protein', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plan', to='App.dietplanner')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('exercise_reps', models.PositiveIntegerField()),
                ('exercise_delay', models.CharField(max_length=255)),
                ('exercise_sets', models.PositiveIntegerField()),
                ('exercise_duration', models.CharField(max_length=255)),
                ('muscle_groups', models.JSONField(default=list)),
                ('equipment_needed', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(max_length=255)),
                ('day_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='App.dayworkout')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=255)),
                ('ingredients', models.JSONField(default=list)),
                ('portion_size', models.CharField(max_length=255)),
                ('calories', models.CharField(blank=True, max_length=255, null=True)),
                ('protein', models.CharField(blank=True, max_length=255, null=True)),
                ('carbs', models.CharField(blank=True, max_length=255, null=True)),
                ('fats', models.CharField(blank=True, max_length=255, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=255, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='App.daymealplan')),
            ],
        ),
        migrations.AddField(
            model_name='dietplanner',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_planner', to='App.personalinfo'),
        ),
        migrations.CreateModel(
            name='WorkoutPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_days', models.JSONField(default=list)),
                ('progression_notes', models.CharField(max_length=255)),
                ('safety_tips', models.CharField(max_length=255)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='App.personalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='dayworkout',
            name='workout_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='App.workoutplanner'),
        ),
    ]
